### ISSUE TITLE
Change Matomo opt-out behaviour from iframe to AJAX requests

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1108]
I would like to change the Matomo behaviour for opting out of tracking. Currently we use an iframe which is blocked by all major ad blocking browser extensions. This leaves a lot of space at the bottom of the page which is not used.

I suggest installing [Ajax Opt Out](https://plugins.matomo.org/AjaxOptOut) for Matomo. This plugin provides an API endpoint to handle opting in/out of tracking. Then we can remove the iframe and add a smaller button to the bottom left of the page to handle opting in/out.

The idea is that the button will stay expanded until the user has dismissed it (e.g., clicks on "Continue") or has opted out. The button will stay at all times.

To give an impression of the button (not expanded):
![Screenshot 2021-06-29 at 19-47-15 GEWIS Website](https://user-images.githubusercontent.com/4983571/123844062-df10f000-d912-11eb-8ab1-3025938104cc.png)

When expanded, the button will display the opt-out text and button with a link to the privacy policy.

**Comment by tomudding** [comment]
HTML and CSS used in the above image (pop-up not present):

```html
<div class="privacy-widget">
    <div class="gi gewis-base"></div>
</div>
```

```css
.privacy-widget {
    left: 1rem;
    bottom: 1rem;
    width: 4rem !important;
    height: 4rem !important;
    background-color: #D40026;
    z-index: 10000;
    margin: 0;
    display: block;
    border-radius: 33%;
    position: fixed;
    font-size: 3rem;
    box-shadow: 4px 4px 15px 0px rgba(0,0,0,0.5);
    cursor: pointer;
}

.privacy-widget > .gewis-base {
    height: 100%;
    width: 100%;
    text-align: center;
    color: #FFFFFF;
    display: inline-block;
}
```
