### ISSUE TITLE
Cancel running workflow jobs if new updates are pushed

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1555]
Sometimes it happens that a lot of force pushes or rebased are pushed to a PR. Stale workflows that were started will still run till they are done. These workflow jobs can be cancelled by adding something like this to the action:

```yml
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
```
